In [1]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Markdown referece can be found here:
    http://nestacms.com/docs/creating-content/markdown-cheat-sheet

Q1. Why would it be a problem if our training set and test set are the same.

<pre> Remember the puporse of machine learning is to be able to generalize with data the algorithm has never seen.

If you train and test with the same data, you are evaluating the performance on the same peace of data. Therefore, you would not be able to know whether the algorithm actually would perform on unseen data. </pre>

Q2. Explain step by step the process to select k in the k-nearest neighbor algorithm (pseudocode)

<pre> The rule of thumb is to start with k as the square root of n (the number of training examples). K should also be odd in most cases to avoid ties. We can then lower k, which will decrease bias but increase variance, or increase k, which would increase bias but decrease variance. We can decide which way to change k depending on the problem we are trying to solve. 

Read the following discussion for more info (K-Fold Cross Validation)
https://www.researchgate.net/post/How_can_we_find_the_optimum_K_in_K-Nearest_Neighbor
</pre>

Q3. For the k-nearest regression. What happends when k = n. Where n is equal tot he training size.

<pre> If we set k = n, the prediction will be the same for any new data point -> Average of all poins in the training set. </pre>

Q4. Define a function that takes a 1-d numpy array, a parameter k, and a number p.
The function returns an estimate equal to the mean of the closest k points to the number p

In [2]:
def k_neighbor(input_data, k, p):
    """Returns the k-neighbor estimate for p using data input_data.

    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    """
    arr = (((p - input_data)**2))**0.5
    ind = np.argpartition(arr, k)[:k]
    return(np.mean(input_data[ind]))
    #YOUR CODE HERE
    
    
    #return answer

In [3]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor(input_data=data, k=3, p=5))
print(k_neighbor(input_data=data, k=2, p=15))
print(k_neighbor(input_data=data, k=3, p=25))
print(k_neighbor(input_data=data, k=1, p=55))
print(k_neighbor(input_data=data, k=3, p=55))
print(k_neighbor(input_data=data, k=10, p=55))

5.33333333333
14.0
26.0
40.0
31.3333333333
19.6


Q5. Similar to Q4 but for the n dimentional case. 

In [8]:
def l1_norm(a,b):
    """Returns the l1 norm (a,b)"""
    return sum(abs(a - b))
    
def l2_norm(a,b):
    """Returns the l2 norm (a,b)""" 
    return (sum((b - a)**2))**0.5
    
def k_neighbor_nd(input_data, k, p, metric='l1', mode='mean'):
    """Returns the k-neighbor estimate for p using data input_data.

    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    metric -- l1 or l2. l1 norm or l2 norm https://en.wikipedia.org/wiki/Norm_(mathematics)
    mode -- estimator possible values = 'mean', 'median', 'max'
    
    Implement the l1 and l2 norms
    for mean, median and max, use np.mean, np.median and np.max
    """
    
    #YOUR CODE HERE
    if metric == 'l1':
        arr = np.zeros(0)
        for i in range(0, input_data.shape[0]):
            arr = np.append(arr, l1_norm(p, input_data[i]))
            
    if metric == 'l2':
        arr = np.zeros(0)
        for i in range(0, input_data.shape[0]):
            arr = np.append(arr, l2_norm(p, input_data[i]))
            
            
    ind = np.argpartition(arr, k)[:k]
    
    if mode == 'mean':
        return(np.mean(input_data[ind], axis = 0))
    
    if mode == 'median':
        return(np.median(input_data[ind], axis = 0))
    
    if mode == 'max':
        return(np.max(input_data[ind], axis = 0))
    
    #return answer
    
   

In [5]:
data_4d = np.array([[4, 1, 2, 1], [1, 4, 2, 0], [3, 3, 1, 1], 
        [4, 0, 0, 0], [1, 2, 0, 0], [3, 4, 2, 3], 
        [2, 4, 4, 2], [2, 1, 4, 1], [3, 3, 2, 4], 
        [4, 3, 0, 4], [2, 2, 4, 0],[4, 3, 0, 2], 
        [4, 3, 0, 2], [0, 3, 4, 2]])

In [9]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l1', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l1', mode='median'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l2', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l2', mode='median'))

[ 2.          2.33333333  4.          1.        ]
[ 4.  3.  0.  2.]
[4 4 2 4]
[ 3.  3.  2.  4.]
[ 3.  4.  2.  3.]
[ 1.33333333  2.          4.          1.        ]
[ 3.5  3.   0.5  1.5]
[4 4 2 4]
[ 3.  3.  2.  4.]
[ 3.  4.  2.  3.]


Q6. Read the documentation on KNeighborsRegressor

http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
    
Explore the source code:
    https://github.com/scikit-learn/scikit-learn/blob/ef5cb84a/sklearn/neighbors/regression.py
        
How different it is from your implementation? How well can you follow the code? Did you learn something new?

<pre> Each person will have a different experience
</pre>